Christmas Crackers Event
Malivil/TTT-Randomat-20-Jingle-Jam-2023 pull request #2
Opened 2024-04-07 07:26 UTC by TheStig294

2024-04-07 12:03 UTC, Malivil requested changes

2024-04-07 12:03 UTC, Malivil commented on lua/randomat2/events/crackers.lua
> +        for _, ent in ipairs(ents.GetAll()) do
```suggestion
        for _, ent in ents.Iterator() do
```

2024-04-07 12:03 UTC, Malivil commented on lua/randomat2/events/crackers.lua
> +    for _, ent in ipairs(ents.GetAll()) do
```suggestion
    for _, ent in ents.Iterator() do
```

2024-04-07 12:03 UTC, Malivil commented on gamemodes/terrortown/entities/weapons/weapon_ttt_cracker.lua
> +        local TraceResult = util.TraceHull({
```suggestion
        local traceResult = util.TraceHull({
```

2024-04-07 12:03 UTC, Malivil commented on gamemodes/terrortown/entities/weapons/weapon_ttt_cracker.lua
> +        return TraceResult.Entity
```suggestion
        return traceResult.Entity
```

2024-04-07 12:03 UTC, Malivil commented on gamemodes/terrortown/entities/weapons/weapon_ttt_cracker.lua
> +            if owner:KeyDown(IN_BACK) or (partner:KeyDown(IN_ATTACK) and partner:KeyDown(IN_BACK)) then
Why does only the partner need to hold left-click?

2024-04-07 12:03 UTC, Malivil commented on gamemodes/terrortown/entities/weapons/weapon_ttt_cracker.lua
> +    function SWEP:GetViewModelPosition(EyePos, EyeAng)
Nit: All local variables should be camelCase, not PascalCase

2024-04-08 05:19 UTC, TheStig294 commented on gamemodes/terrortown/entities/weapons/weapon_ttt_cracker.lua
> +            if owner:KeyDown(IN_BACK) or (partner:KeyDown(IN_ATTACK) and partner:KeyDown(IN_BACK)) then
Because the owner holding left-click has already been checked at line 313

2024-04-08 11:36 UTC, Malivil approved these changes
LGTM

2024-04-09 02:34 UTC, merged